#!/usr/bin/env bun
/**
 * Build script that reads all asset files from _agents/ and config/
 * and generates src/generated/embedded-assets.ts with contents as string literals.
 *
 * Run with: bun run scripts/bundle-assets.ts
 */

import { Glob } from "bun";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";

const ASSET_DIRS = ["_agents", "config"];
const OUTPUT_FILE = "src/generated/embedded-assets.ts";

interface CollectedAssets {
  files: Map<string, string>;
  directories: Set<string>;
}

async function collectAssets(): Promise<CollectedAssets> {
  const files = new Map<string, string>();
  const directories = new Set<string>();

  for (const dir of ASSET_DIRS) {
    // Add the root directory
    directories.add(dir);

    const glob = new Glob("**/*.md");
    for await (const file of glob.scan(dir)) {
      const relativePath = `${dir}/${file}`;
      const content = await Bun.file(relativePath).text();
      files.set(relativePath, content);

      // Collect all parent directories
      let current = dirname(relativePath);
      while (current && current !== ".") {
        directories.add(current);
        current = dirname(current);
      }
    }
  }

  return { files, directories };
}

function escapeForTemplate(content: string): string {
  // Escape backslashes first, then backticks and ${} for template literals
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

async function generateCode(assets: CollectedAssets): Promise<string> {
  const entries: string[] = [];

  // Sort files for consistent output
  const sortedPaths = [...assets.files.keys()].sort();

  for (const path of sortedPaths) {
    const content = assets.files.get(path)!;
    const escaped = escapeForTemplate(content);
    entries.push(`  "${path}": \`${escaped}\``);
  }

  const sortedDirs = [...assets.directories].sort();

  return `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/bundle-assets.ts
// Run "bun run prebuild" to regenerate

export const EMBEDDED_ASSETS: Record<string, string> = {
${entries.join(",\n")}
};

export const ASSET_DIRECTORIES: string[] = [
${sortedDirs.map((d) => `  "${d}"`).join(",\n")}
];
`;
}

async function main() {
  console.log("Bundling assets...");

  const assets = await collectAssets();
  console.log(`Found ${assets.files.size} files to embed`);
  console.log(`Found ${assets.directories.size} directories`);

  const code = await generateCode(assets);

  // Ensure output directory exists
  await mkdir("src/generated", { recursive: true });
  await Bun.write(OUTPUT_FILE, code);

  console.log(`Generated ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error("Failed to bundle assets:", error);
  process.exit(1);
});
